
(function(){
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m])); const escA=s=>esc(s).replace(/"/g,'&quot;'); const uid=()=>Math.random().toString(36).slice(2,9); const has=v=>String(v||'').trim().length>0;
const DETAIL_FIELDS=[['name','Full name'],['pronouns','Pronouns'],['title','Title'],['company','Company'],['department','Department'],['email','Email'],['phone','Phone'],['mobile','Mobile'],['address','Address'],['website','Website'],['tagline','Tagline'],['ctaText','CTA text'],['ctaUrl','CTA URL'],['disclaimer','Disclaimer']];
const IMAGE_FIELDS=[['profile','Profile photo'],['logo','Logo'],['banner','Banner image'],['background','Background/accent image'],['signature','Drawn/uploaded signature image']];
const CORE_CARDS=['profile','logo','name','pronouns','title','company','department','email','phone','mobile','address','website','tagline','socials','banner','backgroundPanel','signature','cta','disclaimer'];
const DEFAULT_ICONS={email:'email',phone:'phone-call',mobile:'phone-call',address:'map-pin',website:'website',company:'briefcase',department:'account',cta:'calendar',socials:'links'};
let icons=[], iconByName={};
let state={device:'desktop',mode:'light',iconSize:16,iconStyle:'outline',fields:{name:'',pronouns:'',title:'',company:'',department:'',email:'',phone:'',mobile:'',address:'',website:'',tagline:'',ctaText:'',ctaUrl:'',disclaimer:''},images:{profile:'',logo:'',banner:'',background:'',signature:''},style:{font:'Segoe UI, Arial, sans-serif',fontSize:13,nameSize:19,widthDesktop:560,widthMobile:340,color:'#3f3f3f',muted:'#666666',accent:'#1d66d3',bg:'#ffffff',line:'#d6d6d6',iconStyle:'outline',iconTint:'default'},icons:Object.assign({},DEFAULT_ICONS),socials:[],customFields:[],layout:[{id:uid(),dir:'horizontal',blocks:['profile','name','title','company']},{id:uid(),dir:'horizontal',blocks:['email','phone','website']},{id:uid(),dir:'vertical',blocks:['address','socials']}]};
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',1800)}
function normUrl(u){u=String(u||'').trim(); if(!u||u==='#')return u; return /^https?:|^mailto:|^tel:/i.test(u)?u:'https://'+u}
function abs(path){return path&&path.startsWith('/')?location.origin+path:path}
function fieldLabel(k){return (DETAIL_FIELDS.find(x=>x[0]===k)||[])[1] || (k.startsWith('custom:')?(state.customFields.find(c=>'custom:'+c.id===k)?.label||'Custom'):k)}
function inLayout(k){return state.layout.some(r=>r.blocks.includes(k))}
function allCards(){return CORE_CARDS.concat(state.customFields.map(c=>'custom:'+c.id))}
async function loadIcons(){try{let m=await fetch('/icons/manifest.json').then(r=>r.json()); icons=m.icons||m||[]; if(!Array.isArray(icons)) icons=[]; icons.forEach(i=>{iconByName[i.name||i.id||i]=i});}catch(e){icons=['email','phone-call','map-pin','website','linkedin','facebook','whatsapp','instagram','youtube','x','calendar','user','home','fax','sms','links'].map(name=>({name}));} }
function iconPath(name,size=24,style){name=name||'info'; style=style||state.style.iconStyle||'outline'; return location.origin+'/icons/png/'+size+'/'+style+'/'+name+'.png'}
function iconImg(name,size){ if(!name)return ''; return '<img src="'+escA(iconPath(name,size||state.iconSize||16))+'" width="'+(size||state.iconSize||16)+'" height="'+(size||state.iconSize||16)+'" style="border:0;vertical-align:-3px;margin-right:5px;width:'+(size||state.iconSize||16)+'px;height:'+(size||state.iconSize||16)+'px">'}
function setDeep(obj,k,v){obj[k]=v; updatePreviewAndOutput(); localStorage.setItem('sigStudioV11',JSON.stringify(state));}
function bindStableInputs(){
  $('infoFields').innerHTML=DETAIL_FIELDS.map(([k,l])=>'<div class="field"><label>'+l+'</label><input id="f_'+k+'" value="'+escA(state.fields[k])+'" placeholder="'+l+'"></div>').join('');
  DETAIL_FIELDS.forEach(([k])=>{$('f_'+k).addEventListener('input',e=>setDeep(state.fields,k,e.target.value));});
  $('imageFields').innerHTML=IMAGE_FIELDS.map(([k,l])=>'<div class="field"><label>'+l+' URL</label><input id="img_'+k+'" value="'+escA(state.images[k])+'" placeholder="https://... or /u/image.png"></div>').join('');
  IMAGE_FIELDS.forEach(([k])=>{$('img_'+k).addEventListener('input',e=>setDeep(state.images,k,e.target.value));});
  const styleFields=[['font','Font stack','select'],['fontSize','Base size','number'],['nameSize','Name size','number'],['widthDesktop','Desktop width','number'],['widthMobile','Mobile width','number'],['color','Text','color'],['muted','Muted','color'],['accent','Accent','color'],['bg','Background','color'],['line','Line','color'],['iconStyle','Icon style','select']];
  $('styleFields').innerHTML=styleFields.map(([k,l,t])=>{let v=state.style[k]; if(k==='font')return '<div class="field"><label>'+l+'</label><select id="s_'+k+'"><option>Segoe UI, Arial, sans-serif</option><option>Arial, Helvetica, sans-serif</option><option>Calibri, Arial, sans-serif</option><option>Georgia, Times New Roman, serif</option><option>Trebuchet MS, Arial, sans-serif</option><option>Verdana, Arial, sans-serif</option></select></div>'; if(k==='iconStyle')return '<div class="field"><label>'+l+'</label><select id="s_'+k+'"><option value="outline">outline</option><option value="solid">solid</option><option value="orange-accent">orange-accent</option></select></div>'; return '<div class="field"><label>'+l+'</label><input id="s_'+k+'" type="'+t+'" value="'+escA(v)+'"></div>'}).join('');
  styleFields.forEach(([k])=>{let el=$('s_'+k); el.value=state.style[k]; el.addEventListener('input',e=>{let v=e.target.value; if(['fontSize','nameSize','widthDesktop','widthMobile'].includes(k))v=parseInt(v||0,10); setDeep(state.style,k,v); renderIconControls();});});
  renderIconControls(); renderSocials(); renderCustomFields();
}
function renderIconControls(){let opts=icons.map(i=>'<option value="'+escA(i.name)+'">'+esc(i.name)+'</option>').join(''); let keys=['email','phone','mobile','address','website','company','department','cta','socials'].concat(state.customFields.map(c=>'custom:'+c.id)); $('iconControls').innerHTML=keys.map(k=>'<div class="iconRow"><label style="display:block;font-size:12px;color:#dbe6f5;margin-bottom:5px">'+fieldLabel(k)+'</label><select data-iconkey="'+escA(k)+'">'+opts+'</select></div>').join(''); document.querySelectorAll('[data-iconkey]').forEach(sel=>{sel.value=state.icons[sel.dataset.iconkey]||'info'; sel.onchange=e=>{state.icons[sel.dataset.iconkey]=e.target.value; updatePreviewAndOutput(); renderBuilder();};});}
function renderCustomFields(){ $('customFields').innerHTML=state.customFields.map(c=>'<div class="customRow"><div class="field"><label>Label</label><input data-c-label="'+c.id+'" value="'+escA(c.label)+'"></div><div class="field"><label>Value</label><input data-c-value="'+c.id+'" value="'+escA(c.value)+'"></div><button class="btn small ghost" data-c-add="'+c.id+'" type="button">Add/move card</button> <button class="btn small danger" data-c-del="'+c.id+'" type="button">Delete</button></div>').join(''); document.querySelectorAll('[data-c-label]').forEach(i=>i.oninput=e=>{let c=state.customFields.find(x=>x.id===i.dataset.cLabel); c.label=e.target.value; updatePreviewAndOutput(); renderBuilder(); renderIconControls();}); document.querySelectorAll('[data-c-value]').forEach(i=>i.oninput=e=>{let c=state.customFields.find(x=>x.id===i.dataset.cValue); c.value=e.target.value; updatePreviewAndOutput();}); document.querySelectorAll('[data-c-add]').forEach(b=>b.onclick=()=>{addCard('custom:'+b.dataset.cAdd);}); document.querySelectorAll('[data-c-del]').forEach(b=>b.onclick=()=>{let k='custom:'+b.dataset.cDel; state.customFields=state.customFields.filter(c=>c.id!==b.dataset.cDel); removeCardEverywhere(k); renderCustomFields(); renderIconControls(); renderBuilder(); updatePreviewAndOutput();});}
$('addCustomBtn').onclick=function(){let id=uid(); state.customFields.push({id,label:'Custom field',value:''}); state.icons['custom:'+id]='info'; renderCustomFields(); renderIconControls(); renderBuilder();}
function renderSocials(){const platforms=['linkedin','facebook','instagram','youtube','x','tiktok','whatsapp','behance','dribbble','calendar','website','custom']; $('socialRows').innerHTML=state.socials.map((s,i)=>'<div class="socialRow"><div class="row2"><div class="field"><label>Platform</label><select data-social-type="'+i+'">'+platforms.map(p=>'<option '+(s.type===p?'selected':'')+'>'+p+'</option>').join('')+'</select></div><div class="field"><label>URL</label><input data-social-url="'+i+'" value="'+escA(s.url||'')+'"></div></div><button class="btn small danger" data-social-del="'+i+'" type="button">Remove</button></div>').join('') || '<div class="note">No social links yet.</div>'; document.querySelectorAll('[data-social-type]').forEach(el=>el.onchange=e=>{state.socials[+el.dataset.socialType].type=e.target.value; updatePreviewAndOutput();}); document.querySelectorAll('[data-social-url]').forEach(el=>el.oninput=e=>{state.socials[+el.dataset.socialUrl].url=e.target.value; updatePreviewAndOutput();}); document.querySelectorAll('[data-social-del]').forEach(b=>b.onclick=()=>{state.socials.splice(+b.dataset.socialDel,1); renderSocials(); updatePreviewAndOutput();});}
$('addSocialBtn').onclick=function(){state.socials.push({type:'linkedin',url:''}); if(!inLayout('socials'))addCard('socials'); renderSocials(); updatePreviewAndOutput();}
function renderBuilder(){const used=new Set(state.layout.flatMap(r=>r.blocks)); $('palette').innerHTML=allCards().filter(k=>!used.has(k)).map(cardHtml).join('') || '<div class="fine">Every available card is in the layout.</div>'; $('layoutRows').innerHTML=state.layout.map((r,ri)=>'<div class="zone" data-row="'+r.id+'"><div class="zonebar"><div class="zoneTitle">'+(r.dir==='horizontal'?'Horizontal row / columns':'Vertical row / stack')+'</div><div class="zoneBtns"><button class="mini" data-toggle-row="'+r.id+'">Toggle</button><button class="mini" data-add-after="'+ri+'">+ Row below</button><button class="mini" data-del-row="'+r.id+'">Delete row</button></div></div><div class="blocks '+r.dir+'" data-drop-row="'+r.id+'">'+r.blocks.map(cardHtml).join('')+'</div></div>').join(''); enableDnD(); document.querySelectorAll('[data-toggle-row]').forEach(b=>b.onclick=()=>{let r=state.layout.find(x=>x.id===b.dataset.toggleRow); r.dir=r.dir==='horizontal'?'vertical':'horizontal'; renderBuilder(); updatePreviewAndOutput();}); document.querySelectorAll('[data-del-row]').forEach(b=>b.onclick=()=>{state.layout=state.layout.filter(r=>r.id!==b.dataset.delRow); renderBuilder(); updatePreviewAndOutput();}); document.querySelectorAll('[data-add-after]').forEach(b=>b.onclick=()=>{state.layout.splice(+b.dataset.addAfter+1,0,{id:uid(),dir:'vertical',blocks:[]}); renderBuilder();}); document.querySelectorAll('[data-remove-card]').forEach(b=>b.onclick=()=>{removeCardEverywhere(b.dataset.removeCard); renderBuilder(); updatePreviewAndOutput();});}
function cardHtml(k){let icon=state.icons[k]||DEFAULT_ICONS[k]||k.replace('socials','links').replace('backgroundPanel','image'); return '<div class="block" draggable="true" data-card="'+escA(k)+'"><div><div class="btitle">'+iconImg(icon,16)+esc(fieldLabel(k))+'</div><small>'+esc(k)+'</small></div><button class="chipx" data-remove-card="'+escA(k)+'" type="button">×</button></div>'}
function removeCardEverywhere(k){state.layout.forEach(r=>r.blocks=r.blocks.filter(b=>b!==k));}
function addCard(k){ if(!inLayout(k)){ if(!state.layout.length)state.layout.push({id:uid(),dir:'vertical',blocks:[]}); state.layout[state.layout.length-1].blocks.push(k); renderBuilder(); updatePreviewAndOutput();}}
$('addVRow').onclick=()=>{state.layout.push({id:uid(),dir:'vertical',blocks:[]}); renderBuilder();}; $('addHRow').onclick=()=>{state.layout.push({id:uid(),dir:'horizontal',blocks:[]}); renderBuilder();}; $('addAllMissing').onclick=()=>{let missing=allCards().filter(k=>!inLayout(k)); if(missing.length)state.layout.push({id:uid(),dir:'vertical',blocks:missing}); renderBuilder(); updatePreviewAndOutput();};
function enableDnD(){document.querySelectorAll('[data-card]').forEach(el=>{el.ondragstart=e=>{e.dataTransfer.setData('text/plain',el.dataset.card);};}); document.querySelectorAll('[data-drop-row],#palette').forEach(zone=>{zone.ondragover=e=>{e.preventDefault();zone.classList.add('dragover')}; zone.ondragleave=()=>zone.classList.remove('dragover'); zone.ondrop=e=>{e.preventDefault(); zone.classList.remove('dragover'); let k=e.dataTransfer.getData('text/plain'); removeCardEverywhere(k); if(zone.id!=='palette'){let r=state.layout.find(x=>x.id===zone.dataset.dropRow); if(r)r.blocks.push(k);} renderBuilder(); updatePreviewAndOutput();};});}
function makeTemplates(){const cats=['common','photo','logo','banner','background','compact','social','cta','legal','creative']; const t=[]; const add=(name,cat,layout)=>t.push({id:'tpl'+t.length,name,cat,layout});
add('Most common left photo', 'common', [['horizontal',['profile','name','title','company']],['vertical',['email','phone','website','address']]]);
add('Most common logo left', 'common', [['horizontal',['logo','name','title','company']],['horizontal',['email','phone','website']],['vertical',['address']]]);
add('Plain professional', 'common', [['vertical',['name','title','company','email','phone','website','address']]]);
add('Compact mobile first', 'common', [['vertical',['name','title','company','email','mobile']]]);
add('Executive stacked', 'common', [['vertical',['name','title','company']],['horizontal',['email','phone']],['vertical',['address','website']]]);
add('Card with banner', 'banner', [['vertical',['name','title','company']],['horizontal',['email','phone','website']],['vertical',['banner']]]);
add('Banner first', 'banner', [['vertical',['banner','name','title','company','email','phone']]]);
add('Logo and CTA', 'cta', [['horizontal',['logo','name','title']],['horizontal',['email','phone','cta']]]);
add('Calendar CTA', 'cta', [['vertical',['signature','name','title','company']],['horizontal',['email','website','cta']]]);
add('Legal footer', 'legal', [['vertical',['name','title','company','email','phone','disclaimer']]]);
add('Social row below', 'social', [['vertical',['name','title','company']],['horizontal',['email','phone','website']],['horizontal',['socials']]]);
add('Profile with socials', 'social', [['horizontal',['profile','name','title','company','socials']],['vertical',['email','phone','address']]]);
add('Background hero', 'background', [['vertical',['backgroundPanel']],['horizontal',['email','phone','website']]]);
add('Real estate split image', 'photo', [['horizontal',['name','title','email','phone','address','profile']]]);
add('Circular portrait stack', 'photo', [['vertical',['profile','name','title','company','socials','email','phone']]]);
add('Logo top centered', 'logo', [['vertical',['logo','name','title','company','email','phone','website']]]);
add('Agency horizontal card', 'creative', [['horizontal',['logo','name','title','socials']],['vertical',['banner','cta']]]);
add('Tattoo style banner', 'creative', [['horizontal',['logo','name','title']],['horizontal',['address','phone','website']],['vertical',['banner']]]);
add('Designer portfolio', 'creative', [['horizontal',['profile','name','title']],['horizontal',['email','website']],['horizontal',['socials','cta']]]);
add('Support contact bar', 'common', [['horizontal',['name','title','company']],['horizontal',['email','phone','mobile','website']]]);
const a=['profile','logo','name','title','company','email','phone','mobile','address','website','socials','banner','cta','signature','disclaimer'];
for(let i=0;i<80;i++){let fam=i%10; let name=['Two-column contact','Photo badge','Logo rail','Banner footer','Social-heavy','CTA card','Legal compact','Background panel','Minimal stack','Mixed grid'][fam]+' '+(Math.floor(i/10)+1); let cat=cats[(i%cats.length)]; let layout; if(fam===0)layout=[['horizontal',['name','title','company']],['horizontal',['email','phone','address']]]; if(fam===1)layout=[['horizontal',['profile','name','title']],['horizontal',[i%2?'email':'mobile','website','socials']]]; if(fam===2)layout=[['horizontal',['logo','name','company']],['vertical',['title','email','phone']]]; if(fam===3)layout=[['vertical',['name','title','company','banner']],['horizontal',['email','phone','website']]]; if(fam===4)layout=[['vertical',['name','title','socials']],['horizontal',['email','website']]]; if(fam===5)layout=[['horizontal',['profile','name','title','cta']],['horizontal',['email','phone']]]; if(fam===6)layout=[['vertical',['name','company','email','phone','disclaimer']]]; if(fam===7)layout=[['vertical',['backgroundPanel','socials']]]; if(fam===8)layout=[['vertical',['name','title',i%3?'email':'website']]]; if(fam===9)layout=[['horizontal',['logo','name','title']],['horizontal',['email','phone','mobile']],['horizontal',['address','website']]]; if(i%4===0)layout.push(['vertical',['signature']]); if(i%5===0)layout.push(['horizontal',['socials']]); add(name,cat,layout);}
return t;}
const templates=makeTemplates();
function renderTemplates(){let cats=[...new Set(templates.map(t=>t.cat))]; $('tplFilter').innerHTML='<option value="all">All categories</option>'+cats.map(c=>'<option value="'+c+'">'+c+'</option>').join(''); const draw=()=>{let q=$('tplSearch').value.toLowerCase(), f=$('tplFilter').value; $('templates').innerHTML=templates.filter(t=>(f==='all'||t.cat===f)&&(!q||t.name.toLowerCase().includes(q)||t.cat.includes(q))).map(t=>'<div class="tpl"><div class="tplTop"><div class="tplName">'+esc(t.name)+'</div><div class="badge">'+esc(t.cat)+'</div></div><div class="tplPrev">'+renderSignature(true,layoutFromTemplate(t),sampleData(),true)+'</div><button data-apply-tpl="'+t.id+'" type="button">Apply structure</button></div>').join(''); document.querySelectorAll('[data-apply-tpl]').forEach(b=>b.onclick=()=>{let t=templates.find(x=>x.id===b.dataset.applyTpl); state.layout=layoutFromTemplate(t); renderBuilder(); updatePreviewAndOutput(); toast('Template applied')});}; $('tplSearch').oninput=draw; $('tplFilter').onchange=draw; draw();}
function layoutFromTemplate(t){return t.layout.map(([dir,blocks])=>({id:uid(),dir,blocks:blocks.filter(Boolean)}));}
function sampleData(){return {fields:{name:'Alex Morgan',pronouns:'',title:'Operations Manager',company:'Company Name',department:'',email:'alex@example.com',phone:'555-212-3721',mobile:'555-605-0743',address:'123 Main Street, City, ST',website:'example.com',tagline:'Building better connections',ctaText:'Book a demo',ctaUrl:'#',disclaimer:'Confidentiality notice and legal footer.'},images:{profile:'/icons/preview/solid-preview.jpg',logo:'',banner:'/icons/preview/orange-accent-preview.jpg',background:'/icons/preview/outline-preview.jpg',signature:''},style:state.style,icons:state.icons,socials:[{type:'linkedin',url:'#'},{type:'facebook',url:'#'},{type:'whatsapp',url:'#'}],customFields:[],layout:state.layout};}
function getData(){return state;}
function renderSignature(mobile=false,layoutOverride=null,dataOverride=null,mini=false){let d=dataOverride||getData(), s=d.style, f=d.fields, img=d.images, layout=layoutOverride||d.layout, width=mini?175:(mobile?s.widthMobile:s.widthDesktop); let rows=layout.map(r=>rowHTML(r,d,mobile,mini)).join(''); return '<table cellpadding="0" cellspacing="0" border="0" width="'+width+'" style="border-collapse:collapse;width:'+width+'px;max-width:100%;font-family:'+s.font+';font-size:'+(mini?10:s.fontSize)+'px;color:'+s.color+';background:'+s.bg+'"><tbody>'+rows+'</tbody></table>';}
function rowHTML(r,d,mobile,mini){let cells=r.blocks.map(k=>blockHTML(k,d,mobile,mini)).filter(Boolean); if(!cells.length)return ''; if(mobile||r.dir==='vertical')return cells.map(c=>'<tr><td style="padding:'+(mini?1:4)+'px 0">'+c+'</td></tr>').join(''); return '<tr>'+cells.map(c=>'<td valign="top" style="padding:0 '+(mini?4:12)+'px '+(mini?2:6)+'px 0">'+c+'</td>').join('')+'</tr>';}
function blockHTML(k,d,mobile,mini){let s=d.style,f=d.fields,img=d.images,sz=mini?10:s.fontSize, iconSz=mini?10:(state.iconSize||16); const base='font-family:'+s.font+';font-size:'+sz+'px;color:'+s.color+';line-height:1.35;'; let val=f[k]; if(k.startsWith('custom:')){let c=d.customFields.find(x=>'custom:'+x.id===k); if(!c||!has(c.value))return ''; return '<div style="'+base+'">'+iconImg(d.icons[k]||'info',iconSz)+'<b>'+esc(c.label)+':</b> '+esc(c.value)+'</div>'}
if(['name','pronouns','title','company','department','tagline'].includes(k)){if(!has(f[k]))return ''; let styles={name:'font-size:'+(mini?13:(mobile?Math.min(19,s.nameSize):s.nameSize))+'px;font-weight:800;color:'+s.color, title:'font-weight:700;color:'+s.color, company:'color:'+s.muted, department:'color:'+s.muted, pronouns:'color:'+s.muted, tagline:'color:'+s.accent+';font-style:italic'}; return '<div style="'+base+';'+(styles[k]||'')+'">'+esc(f[k])+'</div>'}
if(['email','phone','mobile','address','website'].includes(k)){if(!has(f[k]))return ''; let href=k==='email'?'mailto:'+f[k]:((k==='phone'||k==='mobile')?'tel:'+f[k]:(k==='website'?normUrl(f[k]):'')); return '<div style="'+base+'white-space:'+(mobile?'normal':'nowrap')+'">'+iconImg(d.icons[k]||DEFAULT_ICONS[k],iconSz)+(href?'<a href="'+escA(href)+'" style="color:'+s.accent+';text-decoration:none">'+esc(k==='website'?f[k].replace(/^https?:\/\//,''):f[k])+'</a>':esc(f[k]))+'</div>'}
if(k==='profile'&&has(img.profile))return '<img src="'+escA(abs(img.profile))+'" width="'+(mini?42:72)+'" style="display:block;border:0;border-radius:50%;width:'+(mini?42:72)+'px;height:'+(mini?42:72)+'px;object-fit:cover">';
if(k==='logo'&&has(img.logo))return '<img src="'+escA(abs(img.logo))+'" width="'+(mini?56:118)+'" style="display:block;border:0;width:'+(mini?56:118)+'px;max-width:100%;height:auto">';
if(k==='banner'&&has(img.banner))return '<img src="'+escA(abs(img.banner))+'" width="'+(mini?165:(mobile?s.widthMobile:s.widthDesktop))+'" style="display:block;border:0;width:'+(mini?165:(mobile?s.widthMobile:s.widthDesktop))+'px;max-width:100%;height:auto">';
if(k==='signature'&&has(img.signature))return '<img src="'+escA(abs(img.signature))+'" width="'+(mini?70:150)+'" style="display:block;border:0;width:'+(mini?70:150)+'px;max-width:100%;height:auto">';
if(k==='socials'&&d.socials.length){let links=d.socials.filter(x=>has(x.url)); if(!links.length)return ''; return '<div>'+links.map(x=>'<a href="'+escA(normUrl(x.url))+'" style="display:inline-block;text-decoration:none;margin-right:'+(mini?3:7)+'px">'+iconImg(x.type,mini?11:18)+'</a>').join('')+'</div>'}
if(k==='cta'&&has(f.ctaText))return '<a href="'+escA(normUrl(f.ctaUrl||f.website||'#'))+'" style="display:inline-block;background:'+s.accent+';color:#fff;text-decoration:none;border-radius:8px;padding:'+(mini?'3px 5px':'8px 12px')+';font-weight:800;font-family:'+s.font+';font-size:'+sz+'px">'+esc(f.ctaText)+'</a>';
if(k==='disclaimer'&&has(f.disclaimer))return '<div style="'+base+'font-size:'+(mini?8:11)+'px;color:'+s.muted+';border-top:1px solid '+s.line+';padding-top:'+(mini?3:8)+'px">'+esc(f.disclaimer)+'</div>';
if(k==='backgroundPanel'){let bg=has(img.background)?'url('+escA(abs(img.background))+') center/cover no-repeat':s.bg; return '<table cellpadding="0" cellspacing="0" border="0" width="100%" style="background:'+bg+';border:1px solid '+s.line+';border-radius:12px"><tr><td style="padding:'+(mini?6:14)+'px">'+blockHTML('name',d,mobile,mini)+blockHTML('title',d,mobile,mini)+blockHTML('company',d,mobile,mini)+blockHTML('email',d,mobile,mini)+blockHTML('phone',d,mobile,mini)+'</td></tr></table>'}
return ''}
function normalizeIphone(html){return html.replace(/font-size\s*:\s*[^;\"]+/gi,'font-size:15px').replace(/font-family\s*:\s*[^;\"]+/gi,'font-family:-apple-system, BlinkMacSystemFont, Segoe UI, Arial, sans-serif').replace(/width:\s*\d+px/gi,'max-width:320px')}
function updatePreviewAndOutput(){localStorage.setItem('sigStudioV11',JSON.stringify(state)); let mobile=['mobile','iphone'].includes(state.device); let html=renderSignature(mobile); $('htmlOut').value=html; $('copyArea').innerHTML=html; $('screen').classList.toggle('dark',state.mode==='dark'); $('compatWarn').innerHTML='Email clients vary. iPhone Mail may flatten font sizes/families. Outlook may not preserve background images or complex CSS. PNG icon images are safer than inline SVG.'; if(state.device==='iphone')$('screen').innerHTML='<div class="iphone"><div class="iphoneTop"><span>Cancel</span><span>New Message</span><span style="color:#007aff">Send</span></div><div class="iosRows"><div>To:</div><div>Cc/Bcc, From:</div><div>Subject:</div></div><div class="iosBody">'+normalizeIphone(html)+'</div></div>'; else if(state.device==='outlookpc')$('screen').innerHTML='<div class="desktopFrame"><div class="mailChrome">Outlook for Windows · New message</div><div class="mailBody">'+html+'</div></div>'; else if(state.device==='gmailpc')$('screen').innerHTML='<div class="desktopFrame"><div class="mailChrome">Gmail desktop · Compose</div><div class="mailBody">'+html+'</div></div>'; else $('screen').innerHTML='<div class="desktopFrame"><div class="mailChrome">'+(mobile?'Mobile preview':'Desktop preview')+'</div><div class="mailBody">'+html+'</div></div>';}
function loadSaved(){try{let saved=localStorage.getItem('sigStudioV11'); if(saved){let x=JSON.parse(saved); state=Object.assign(state,x); state.fields=Object.assign({},state.fields,x.fields||{}); state.images=Object.assign({},state.images,x.images||{}); state.style=Object.assign({},state.style,x.style||{}); state.icons=Object.assign({},state.icons,x.icons||{});}}catch(e){}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('on',x===b)); document.querySelectorAll('.section').forEach(s=>s.classList.remove('on')); $('tab-'+b.dataset.tab).classList.add('on');});
document.querySelectorAll('.deviceTab').forEach(b=>b.onclick=()=>{state.device=b.dataset.device; document.querySelectorAll('.deviceTab').forEach(x=>x.classList.toggle('on',x===b)); updatePreviewAndOutput();}); document.querySelectorAll('.modeBtn').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode; document.querySelectorAll('.modeBtn').forEach(x=>x.classList.toggle('on',x===b)); updatePreviewAndOutput();});
$('copyHtml').onclick=()=>navigator.clipboard.writeText($('htmlOut').value).then(()=>toast('HTML copied')); $('copyVisual').onclick=()=>{let r=document.createRange(); r.selectNodeContents($('copyArea')); let s=window.getSelection(); s.removeAllRanges(); s.addRange(r); document.execCommand('copy'); s.removeAllRanges(); toast('Visual signature copied')}; $('saveLocal').onclick=()=>{localStorage.setItem('sigStudioV11',JSON.stringify(state)); toast('Saved')}; $('loadLocal').onclick=()=>{loadSaved(); bindStableInputs(); renderBuilder(); renderTemplates(); updatePreviewAndOutput(); toast('Loaded')}; $('resetBtn').onclick=()=>{if(confirm('Reset everything?')){localStorage.removeItem('sigStudioV11'); location.reload();}};
$('uploadBtn').onclick=async()=>{let file=$('uploadFile').files[0]; if(!file){$('uploadMsg').textContent='Choose an image first.';return} let fd=new FormData(); fd.append('file',file); fd.append('name',$('uploadName').value||file.name); $('uploadMsg').textContent='Uploading...'; try{let res=await fetch('/api/upload',{method:'POST',body:fd}); let data=await res.json(); if(!data.ok)throw new Error(data.error||'Upload failed'); $('uploadMsg').innerHTML='Hosted URL: <b>'+esc(data.url)+'</b>'; await loadAssets();}catch(e){$('uploadMsg').textContent=e.message}}; $('refreshAssets').onclick=loadAssets;
async function loadAssets(){try{let res=await fetch('/api/list'); let data=await res.json(); if(!data.ok)throw new Error(data.error||'Could not list assets'); $('assetList').innerHTML=data.assets.map(a=>{let full=location.origin+a.url; return '<div class="asset"><b>'+esc(a.name)+'</b><br>'+esc(full)+'<br><button class="btn small ghost" data-copy-url="'+escA(full)+'" type="button">Copy URL</button></div>'}).join('')||'<div class="note">No hosted images yet.</div>'; document.querySelectorAll('[data-copy-url]').forEach(b=>b.onclick=()=>navigator.clipboard.writeText(b.dataset.copyUrl).then(()=>toast('Image URL copied')))}catch(e){$('assetList').innerHTML='<div class="note">'+esc(e.message)+'</div>'}}
const canvas=$('sigCanvas'), ctx=canvas.getContext('2d'); let drawing=false; ctx.lineWidth=3; ctx.lineCap='round'; ctx.strokeStyle='#111'; function pos(e){let r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e; return{x:(p.clientX-r.left)*(canvas.width/r.width),y:(p.clientY-r.top)*(canvas.height/r.height)}} function down(e){drawing=true;let p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()} function move(e){if(!drawing)return;let p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()} function up(){drawing=false} canvas.addEventListener('mousedown',down);canvas.addEventListener('mousemove',move);window.addEventListener('mouseup',up);canvas.addEventListener('touchstart',down,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});canvas.addEventListener('touchend',up); $('clearSig').onclick=()=>ctx.clearRect(0,0,canvas.width,canvas.height); $('saveSig').onclick=()=>{state.images.signature=canvas.toDataURL('image/png'); if(!inLayout('signature'))addCard('signature'); bindStableInputs(); updatePreviewAndOutput(); toast('Drawn signature added');};
(async function init(){await loadIcons(); loadSaved(); bindStableInputs(); renderBuilder(); renderTemplates(); updatePreviewAndOutput(); loadAssets();})();
})();
