name = "signature"
main = "worker.js"
compatibility_date = "2025-01-01"

# This binding name MUST match the code: env.SIG_ASSETS
# Replace the id with your Cloudflare KV namespace ID.
[[kv_namespaces]]
binding = "SIG_ASSETS"
id = "b6395c0429124763bc03e77a73f6c505"
