name = "signature-editor"
main = "worker.js"
compatibility_date = "2026-04-30"

[[kv_namespaces]]
binding = "SIG_ASSETS"
id = "REPLACE_WITH_YOUR_KV_NAMESPACE_ID"

[assets]
directory = "./public"
binding = "ASSETS"
