name = "signature"
main = "worker.js"
compatibility_date = "2026-04-30"

[[kv_namespaces]]
binding = "SIG_ASSETS"
id = "b6395c0429124763bc03e77a73f6c505"

[assets]
directory = "./public"
binding = "ASSETS"
